language: node_js
node_js:
  - '6'
cache:
  yarn: true
branches:
  only:
  - master
script:
  - npm test
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cat ./__coverage__/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi